---
title: "Network Dynamics and Temporality"
always_allow_html: yes
---

# Network Dynamics and Temporality {#ch11}

> It's About Time!

So far in this class we've been mostly working with `static` networks or `snapshots` of dynamic networks. That's enough for most of our needs. However, social networks are dynamic in nature. One important use of SNA is to understand how an network would function given its current structure. Such a question is genuniely about network dynamics.

In Week 11, we explore ...

@Myllari2010-ad

## Temporality

Terms:

- temporal
- dynamics
- longitudinal


what does duration mean?

> The decisions that the historian makes while assembling, cleaning, and representing her data become the objects that the computer manipulates, so these issues are theoretically significant! (From [Exploring Big Historical Data](http://www.themacroscope.org/2.0/dynamic-networks-in-gephi/))

<embed src="http://www.ickn.org/documents/CKN4NAACSOS.pdf" width="100%" height="400px" />

## Tools

Gephi supports analysis of dynamic networks. This website, [Exploring Big Historical Data](http://www.themacroscope.org/2.0/dynamic-networks-in-gephi/), provides a useful introduction.

<iframe width="560" height="315" src="https://www.youtube.com/embed/hKYku8b60Dc" frameborder="0" allowfullscreen></iframe>

R 

@Mascolo2013-sh
